package Lab01_GestionEmpleados;

import java.awt.Font;

public class FrmEmpleados extends javax.swing.JFrame {
    
    //Declaracion de variables globales
    Empleado empleado; // objeto empleado de la clase Empleados
    public FrmEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtxtCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtxtNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jtxtSueldo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtxtHextras = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jcbxSeguro = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jcbxArea = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDatos = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jbtnCrear = new javax.swing.JButton();
        jbtnMostrar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uso de Clases, Objetos, atributos y Métodos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jtxtCodigo.addActionListener(this::jtxtCodigoActionPerformed);
        jtxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtCodigo, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jtxtNombre, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sueldo Base", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jtxtSueldo, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horas Extras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jtxtHextras, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Seguro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jcbxSeguro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbxSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "AFP", "SNP" }));
        jcbxSeguro.addActionListener(this::jcbxSeguroActionPerformed);
        jPanel5.add(jcbxSeguro, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 160, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jcbxArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Sistemas", "Administración", "Marketing" }));
        jPanel6.add(jcbxArea, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 210, -1));

        jtxaDatos.setColumns(20);
        jtxaDatos.setRows(5);
        jScrollPane1.setViewportView(jtxaDatos);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 470, 236));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCrear.setText("Crear Objeto");
        jbtnCrear.addActionListener(this::jbtnCrearActionPerformed);
        jPanel8.add(jbtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 114, 40));

        jbtnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnMostrar.setText("Mostrar infromacion del objeto");
        jbtnMostrar.addActionListener(this::jbtnMostrarActionPerformed);
        jPanel8.add(jbtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 40));

        jbtnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.setOpaque(true);
        jbtnLimpiar.addActionListener(this::jbtnLimpiarActionPerformed);
        jPanel8.add(jbtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 40));

        jbtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.setOpaque(true);
        jbtnSalir.addActionListener(this::jbtnSalirActionPerformed);
        jPanel8.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 40));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 520, 60));

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoActionPerformed

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
        //Capturando la informacion de los empleados de los objetos del formulario
        String cod=jtxtCodigo.getText();
        String nom=jtxtNombre.getText();
        String seguro=jcbxSeguro.getSelectedItem().toString();
        double sueldo=Double.parseDouble(jtxtSueldo.getText());
        double h_extras=Double.parseDouble(jtxtHextras.getText());
        String area=jcbxArea.getSelectedItem().toString();

        //Creando el objeto empleado de la clase Empleados
        empleado=new Empleado(cod,nom,area,sueldo,h_extras,seguro);
    }//GEN-LAST:event_jbtnCrearActionPerformed

    private void jcbxSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxSeguroActionPerformed

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
        //Extrayendo la informacion de los atributos y metodos de la clase
        jtxaDatos.append("Objeto Número         : "+empleado.getContador()+"\n");
        jtxaDatos.append("Codigo                : "+empleado.codigo+"\n");
        jtxaDatos.append("Nombre                : "+empleado.nombre+"\n");
        jtxaDatos.append("Seguro                : "+empleado.tipo_seg+"\n");
        jtxaDatos.append("Sueldo Base           : "+empleado.sueldoBase+"\n");
        jtxaDatos.append("Horas Extras          : "+empleado.horasExtras+"\n");
        jtxaDatos.append("Area                  : "+empleado.area+"\n");
        jtxaDatos.append("Monto Extra           : "+empleado.montoHExtras()+"\n");
        jtxaDatos.append("Monto Seguro          : "+empleado.montoSeguro()+"\n");
        jtxaDatos.append("Monto EsSalud         : "+empleado.montoEssalud()+"\n");
        jtxaDatos.append("Monto de Descuentos   : "+empleado.montoDescuentos()+"\n");
        jtxaDatos.append("Sueldo Bruto          : "+empleado.sueldoBruto()+"\n");
        jtxaDatos.append("Sueldo Neto           : "+empleado.sueldoNeto()+"\n");
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtxaDatos.setFont(new Font("monospaced", Font.PLAIN, 12));
    }//GEN-LAST:event_formWindowOpened

    private void jtxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodigoKeyTyped
    // Si el texto ya tiene 8 o más caracteres, ignoramos la nueva tecla
        if (jtxtCodigo.getText().length() >= 8) {
            evt.consume(); // Esto "destruye" el evento de la tecla antes de que se escriba
        }
    }//GEN-LAST:event_jtxtCodigoKeyTyped

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
    // Limpiar cuadros de texto
        jtxtCodigo.setText("");
        jtxtNombre.setText("");
        jtxtSueldo.setText("");
        jtxtHextras.setText("");

        // Resetear ComboBox al primer elemento (índice 0)
        jcbxSeguro.setSelectedIndex(0);
        jcbxArea.setSelectedIndex(0);

        // Limpiar el área de resultados
        jtxaDatos.setText("");

        // Poner el foco (el cursor) de nuevo en el primer campo
        jtxtCodigo.requestFocus();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println("Error en el Look and Feel: " + ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEmpleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnMostrar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbxArea;
    private javax.swing.JComboBox<String> jcbxSeguro;
    private javax.swing.JTextArea jtxaDatos;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtHextras;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtSueldo;
    // End of variables declaration//GEN-END:variables
}
