package Lab01_GestionEmpleados;

public class FrmJefe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmJefe.class.getName());
    Jefe jefe;
    public FrmJefe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtxtNombres = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtxtDni = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jcbxSexo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jtxtAnios = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jcbxEspecialidad = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jcbxActividad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDatos = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jbtnCrear = new javax.swing.JButton();
        jbtnMostrar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 540));
        setPreferredSize(new java.awt.Dimension(660, 540));
        setResizable(false);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jtxtNombres, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jtxtDni.addActionListener(this::jtxtDniActionPerformed);
        jtxtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDniKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtDni, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 130, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jcbxSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Masculino", "Femenino" }));
        jPanel3.add(jcbxSexo, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 150, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Años Antigüedad ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jtxtAnios.addActionListener(this::jtxtAniosActionPerformed);
        jtxtAnios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAniosKeyTyped(evt);
            }
        });
        jPanel4.add(jtxtAnios, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jcbxEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Gerente", "Subgerente" }));
        jPanel5.add(jcbxEspecialidad, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Área", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jcbxActividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbxActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Contabilidad", "Planificación" }));
        jPanel6.add(jcbxActividad, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 190, -1));

        jtxaDatos.setColumns(20);
        jtxaDatos.setRows(5);
        jScrollPane1.setViewportView(jtxaDatos);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 600, 236));

        jbtnCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCrear.setText("Crear Objeto");
        jbtnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCrear.addActionListener(this::jbtnCrearActionPerformed);

        jbtnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnMostrar.setText("Mostrar infromacion del objeto");
        jbtnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMostrar.addActionListener(this::jbtnMostrarActionPerformed);

        jbtnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.setOpaque(true);
        jbtnLimpiar.addActionListener(this::jbtnLimpiarActionPerformed);

        jbtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.setOpaque(true);
        jbtnSalir.addActionListener(this::jbtnSalirActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 610, 60));

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAniosActionPerformed

    private void jtxtAniosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAniosKeyTyped
    // Solo permite dígitos numéricos
    if (!Character.isDigit(evt.getKeyChar())) {
        evt.consume();
    }
    }//GEN-LAST:event_jtxtAniosKeyTyped

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
    // Validar campos vacíos
    if (jtxtNombres.getText().isEmpty() || jtxtDni.getText().isEmpty()
            || jtxtAnios.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, complete todos los campos.",
                "Campos vacíos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar ComboBox
    if (jcbxSexo.getSelectedIndex()        == 0 ||
        jcbxEspecialidad.getSelectedIndex() == 0 ||
        jcbxActividad.getSelectedIndex()    == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione todas las opciones.",
                "Selección inválida",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que años sea número entero
    int anios;
    try {
        anios = Integer.parseInt(jtxtAnios.getText());
        if (anios < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los años no pueden ser negativos.",
                    "Valor inválido",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Los años deben ser un número entero.",
                "Valor inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Capturando datos del formulario
    String nom   = jtxtNombres.getText();
    String dni   = jtxtDni.getText();
    String sexo  = jcbxSexo.getSelectedItem().toString();
    String cargo = jcbxEspecialidad.getSelectedItem().toString();
    String area  = jcbxActividad.getSelectedItem().toString();

    // Creando el objeto Jefe
    jefe = new Jefe(nom, sexo, dni, cargo, area, anios);

    // Confirmación
    javax.swing.JOptionPane.showMessageDialog(this,
            "Objeto creado correctamente.\nJefe N°: " + Jefe.getContador(),
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnCrearActionPerformed

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
    // Validar que el objeto fue creado
    if (jefe == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Primero debe crear un objeto con 'Crear Objeto'.",
                "Sin datos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Mostrando información
    jtxaDatos.append("Objeto Número         : " + Jefe.getContador()          + "\n");
    jtxaDatos.append("Nombres               : " + jefe.nombres                + "\n");
    jtxaDatos.append("DNI                   : " + jefe.dni                    + "\n");
    jtxaDatos.append("Sexo                  : " + jefe.sexo                   + "\n");
    jtxaDatos.append("Cargo                 : " + jefe.cargo                  + "\n");
    jtxaDatos.append("Área                  : " + jefe.area                   + "\n");
    jtxaDatos.append("Años de Antigüedad    : " + jefe.aniosAntiguedad        + "\n");
    jtxaDatos.append("Sueldo Base           : " + jefe.calcularSueldoBase()   + "\n");
    jtxaDatos.append("Movilidad             : " + jefe.calcularMovilidad()    + "\n");
    jtxaDatos.append("Bonificación          : " + jefe.calcularBonificacion() + "\n");
    jtxaDatos.append("Sueldo Final          : " + jefe.sueldoFinal()          + "\n");
    jtxaDatos.append("----------------------------------------\n");
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
    jtxtNombres.setText("");
    jtxtDni.setText("");
    jtxtAnios.setText("");
    jcbxSexo.setSelectedIndex(0);
    jcbxEspecialidad.setSelectedIndex(0);
    jcbxActividad.setSelectedIndex(0);
    jtxaDatos.setText("");
    jtxtNombres.requestFocus();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jtxtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDniActionPerformed

    private void jtxtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDniKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDniKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmJefe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnMostrar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbxActividad;
    private javax.swing.JComboBox<String> jcbxEspecialidad;
    private javax.swing.JComboBox<String> jcbxSexo;
    private javax.swing.JTextArea jtxaDatos;
    private javax.swing.JTextField jtxtAnios;
    private javax.swing.JTextField jtxtDni;
    private javax.swing.JTextField jtxtNombres;
    // End of variables declaration//GEN-END:variables
}
