package Lab02_Encapsulamiento;

public class FrmDocente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDocente.class.getName());
    Docente docente; // objeto global de la clase Docente

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        jtxaDatos.setFont(new java.awt.Font("monospaced", java.awt.Font.PLAIN, 12));
    }
    /**
     * Creates new form FrmDocente
     */
    public FrmDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtxtNombres = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jcbxPostgrado = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jtxtHoras = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDatos = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jbtnCrear = new javax.swing.JButton();
        jbtnMostrar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Docentes");
        setMinimumSize(new java.awt.Dimension(640, 560));
        setPreferredSize(new java.awt.Dimension(640, 560));
        setResizable(false);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jtxtNombres.addActionListener(this::jtxtNombresActionPerformed);
        jPanel1.add(jtxtNombres, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoría"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jcbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Principal", "Asociado", "Auxiliar" }));
        jPanel2.add(jcbxCategoria, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudios de Postgrado"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jcbxPostgrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Doctorado", "Maestría" }));
        jPanel3.add(jcbxPostgrado, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 190, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas de Clase "));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jtxtHoras.addActionListener(this::jtxtHorasActionPerformed);
        jPanel4.add(jtxtHoras, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 80));

        jtxaDatos.setColumns(20);
        jtxaDatos.setRows(5);
        jScrollPane1.setViewportView(jtxaDatos);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 560, 220));

        jbtnCrear.setText("Crear Objeto");
        jbtnCrear.addActionListener(this::jbtnCrearActionPerformed);

        jbtnMostrar.setText("Mostrar Info del Objeto");
        jbtnMostrar.addActionListener(this::jbtnMostrarActionPerformed);

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(this::jbtnLimpiarActionPerformed);

        jbtnSalir.setText("Salir ");
        jbtnSalir.setToolTipText("");
        jbtnSalir.addActionListener(this::jbtnSalirActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 560, 70));

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombresActionPerformed

    private void jtxtHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHorasActionPerformed

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
    // Validar campos vacíos
    if (jtxtNombres.getText().isEmpty() || jtxtHoras.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, complete todos los campos.",
                "Campos vacíos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar ComboBox
    if (jcbxCategoria.getSelectedIndex() == 0 ||
        jcbxPostgrado.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione todas las opciones.",
                "Selección inválida",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que horas sea número entero válido
    int horas;
    try {
        horas = Integer.parseInt(jtxtHoras.getText());
        if (horas <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Las horas deben ser un número mayor a 0.",
                    "Valor inválido",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Las horas deben ser un número entero.",
                "Valor inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Capturando datos del formulario
    String nom      = jtxtNombres.getText();
    String categoria = jcbxCategoria.getSelectedItem().toString();
    String postgrado = jcbxPostgrado.getSelectedItem().toString();

    // Creando el objeto Docente
    docente = new Docente(nom, categoria, postgrado, horas);

    // Confirmación
    javax.swing.JOptionPane.showMessageDialog(this,
            "Objeto creado correctamente.\nDocente N°: " + Docente.getContador() +
            "\nCódigo: " + docente.getCodigo(),
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnCrearActionPerformed

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
    // Validar que el objeto fue creado
    if (docente == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Primero debe crear un objeto con 'Crear Objeto'.",
                "Sin datos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Mostrando información
    jtxaDatos.append("Objeto Número         : " + Docente.getContador()              + "\n");
    jtxaDatos.append("Código Autogenerado   : " + docente.getCodigo()                + "\n");
    jtxaDatos.append("Nombres               : " + docente.getNombres()               + "\n");
    jtxaDatos.append("Categoría             : " + docente.getCategoria()             + "\n");
    jtxaDatos.append("Estudios de Postgrado : " + docente.getpostgrado()             + "\n");
    jtxaDatos.append("Horas de Clase        : " + docente.getHorasClase()            + "\n");
    jtxaDatos.append("Pago por Hora         : " + docente.getPagoPorHora()           + "\n");
    jtxaDatos.append("Pago Parcial          : " + docente.calcularPagoParcial()      + "\n");
    jtxaDatos.append("Bonificación          : " + docente.calcularBonificacion()     + "\n");
    jtxaDatos.append("Descuento Salud       : " + docente.calcularDescuento()        + "\n");
    jtxaDatos.append("Sueldo Final          : " + docente.calcularSueldoFinal()      + "\n");
    jtxaDatos.append("----------------------------------------\n");
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
    jtxtNombres.setText("");
    jtxtHoras.setText("");
    jcbxCategoria.setSelectedIndex(0);
    jcbxPostgrado.setSelectedIndex(0);
    jtxaDatos.setText("");
    jtxtNombres.requestFocus();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDocente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnMostrar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbxCategoria;
    private javax.swing.JComboBox<String> jcbxPostgrado;
    private javax.swing.JTextArea jtxaDatos;
    private javax.swing.JTextField jtxtHoras;
    private javax.swing.JTextField jtxtNombres;
    // End of variables declaration//GEN-END:variables
}
