package Lab02_Encapsulamiento;

public class FrmTrabajador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmTrabajador.class.getName());
    Trabajador trabajador; // objeto global de la clase Trabajador
    /**
     * Creates new form FrmTrabajador
     */
    public FrmTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtxtNombres = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtxtUnidades = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jcbxContrato = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jtxtHijos = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jcbxAfiliacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDatos = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jbtnCrear = new javax.swing.JButton();
        jbtnMostrar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Trabajadores");
        setMinimumSize(new java.awt.Dimension(640, 560));
        setPreferredSize(new java.awt.Dimension(640, 560));
        setResizable(false);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jtxtNombres.addActionListener(this::jtxtNombresActionPerformed);
        jPanel1.add(jtxtNombres, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidades Producidas"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jtxtUnidades.addActionListener(this::jtxtUnidadesActionPerformed);
        jPanel2.add(jtxtUnidades, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 180, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Contrato"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jcbxContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Contratado", "Estable" }));
        jPanel3.add(jcbxContrato, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 20, 160, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoría"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jcbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "A", "B" }));
        jPanel4.add(jcbxCategoria, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de Hijos"));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jtxtHijos.addActionListener(this::jtxtHijosActionPerformed);
        jPanel5.add(jtxtHijos, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 180, 80));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Afiliación"));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jcbxAfiliacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "AFP", "SNP" }));
        jPanel6.add(jcbxAfiliacion, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 120, 160, 80));

        jtxaDatos.setColumns(20);
        jtxaDatos.setRows(5);
        jScrollPane1.setViewportView(jtxaDatos);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 560, 220));

        jbtnCrear.setText("Crear Objeto");
        jbtnCrear.addActionListener(this::jbtnCrearActionPerformed);

        jbtnMostrar.setText("Mostrar Info del Objeto");
        jbtnMostrar.addActionListener(this::jbtnMostrarActionPerformed);

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(this::jbtnLimpiarActionPerformed);

        jbtnSalir.setText("Salir ");
        jbtnSalir.setToolTipText("");
        jbtnSalir.addActionListener(this::jbtnSalirActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 560, 70));

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombresActionPerformed

    private void jtxtUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUnidadesActionPerformed

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
    // Validar campos vacíos
    if (jtxtNombres.getText().isEmpty() || jtxtUnidades.getText().isEmpty()
            || jtxtHijos.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, complete todos los campos.",
                "Campos vacíos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar ComboBox
    if (jcbxContrato.getSelectedIndex()  == 0 ||
        jcbxCategoria.getSelectedIndex() == 0 ||
        jcbxAfiliacion.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, seleccione todas las opciones.",
                "Selección inválida",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que unidades e hijos sean números válidos
    int unidades, hijos;
    try {
        unidades = Integer.parseInt(jtxtUnidades.getText());
        hijos    = Integer.parseInt(jtxtHijos.getText());
        if (unidades < 0 || hijos < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los valores no pueden ser negativos.",
                    "Valor inválido",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Unidades producidas y número de hijos deben ser números enteros.",
                "Valor inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Capturando datos del formulario
    String nom      = jtxtNombres.getText();
    String contrato = jcbxContrato.getSelectedItem().toString();
    String categoria = jcbxCategoria.getSelectedItem().toString();
    String afiliacion = jcbxAfiliacion.getSelectedItem().toString();

    // Creando el objeto Trabajador
    trabajador = new Trabajador(nom, unidades, contrato, categoria, hijos, afiliacion);

    // Confirmación
    javax.swing.JOptionPane.showMessageDialog(this,
            "Objeto creado correctamente.\nTrabajador N°: " + Trabajador.getContador() +
            "\nCódigo: " + trabajador.getCodigo(),
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jbtnCrearActionPerformed

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
    // Validar que el objeto fue creado
    if (trabajador == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Primero debe crear un objeto con 'Crear Objeto'.",
                "Sin datos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Mostrando información
    jtxaDatos.append("Objeto Número         : " + Trabajador.getContador()              + "\n");
    jtxaDatos.append("Código Autogenerado   : " + trabajador.getCodigo()                + "\n");
    jtxaDatos.append("Nombres               : " + trabajador.getNombres()               + "\n");
    jtxaDatos.append("Tipo de Contrato      : " + trabajador.getTipoContrato()          + "\n");
    jtxaDatos.append("Categoría             : " + trabajador.getCategoria()             + "\n");
    jtxaDatos.append("Unidades Producidas   : " + trabajador.getUnidadesProducidas()    + "\n");
    jtxaDatos.append("Número de Hijos       : " + trabajador.getNumeroHijos()           + "\n");
    jtxaDatos.append("Tipo de Afiliación    : " + trabajador.getTipoAfiliacion()        + "\n");
    jtxaDatos.append("Sueldo Bruto          : " + trabajador.calcularSueldoBruto()      + "\n");
    jtxaDatos.append("Bonificación          : " + trabajador.calcularBonificacion()     + "\n");
    jtxaDatos.append("Descuento             : " + trabajador.calcularDescuento()        + "\n");
    jtxaDatos.append("Sueldo Neto           : " + trabajador.calcularSueldoNeto()       + "\n");
    jtxaDatos.append("----------------------------------------\n");
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
    jtxtNombres.setText("");
    jtxtUnidades.setText("");
    jtxtHijos.setText("");
    jcbxContrato.setSelectedIndex(0);
    jcbxCategoria.setSelectedIndex(0);
    jcbxAfiliacion.setSelectedIndex(0);
    jtxaDatos.setText("");
    jtxtNombres.requestFocus();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jtxtHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHijosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHijosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmTrabajador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnMostrar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbxAfiliacion;
    private javax.swing.JComboBox<String> jcbxCategoria;
    private javax.swing.JComboBox<String> jcbxContrato;
    private javax.swing.JTextArea jtxaDatos;
    private javax.swing.JTextField jtxtHijos;
    private javax.swing.JTextField jtxtNombres;
    private javax.swing.JTextField jtxtUnidades;
    // End of variables declaration//GEN-END:variables
}
